### PR TITLE
Allow variable nesting

### PR DESCRIPTION
**Pull request by travco**
**Line of thought**
I noticed that this plugin _despite supporting nested loops didn't support using the iterators of parent loops_ in the range. Although I understood why you can't have variables in the range that are unresolved and floating about, I didn't understand how even the variables that have been resolved by 'unrolling' the loop couldn't just propagate deeper into the nesting. 

Turns out the code already supported it more or less, the only issue being is that there was no mechanism for detecting what was an was not a local variable to loop nesting. So I built somewhat of a wrapper around the existing code to keep a running stack of what loops we've "dove" into, and had to make a bit of a workaround for trimming the stack when we "exit" a loop.

**Changes**
- Added support for nesting `@for` loops while using variables in the range that are iterators of parent `@for` loops
- Added tests for added functionality
- Migrated and changed the wording on "variables not allowed in range" error to be only for non-local `@for` loop variables (now reads "External variable (not from a parent for loop) cannot be used as a range parameter").
- Added example to README of nested loops

**Example / Added README entry:**
Locality of variables in nested loops is supported:

``` css
@for $x from 1 to 2 { 
    @for $y from 1 to $x { 
        @for $z from $y to $x { 
            .c-$(x)-$(z)-$(y) { padding: $(x)em $(z)em $(y)em; } 
        }
    }
}
```

``` css
.c-1-1-1 {
    padding: 1em 1em 1em
}
.c-2-1-1 {
    padding: 2em 1em 1em
}
.c-2-2-1 {
    padding: 2em 2em 1em
}
.c-2-2-2 {
    padding: 2em 2em 2em
}
```

### CODE REVIEW

**Comment by travco** [comment]
Hey @antyakushev, I don't mean to pester but I'd like to know your thoughts on this, I'm rather eager to get this upstream so I don't have to keep manually defining my repo.

**Comment by antyakushev** [comment]
@travco Thanks, it looks great! Sorry for the delay, I'll publish new version in a moment.

**Comment by antyakushev** [comment]
@travco By the way, why didn’t you just used `precss`? I believe it already has this feature.

**Comment by travco** [comment]
More flavors make the world go round?

Was working in a repo that already relied on simple-vars, so to tack on the part of precss that adds for loops (postcss-advanced-variables) would have also added another set of evalutations for (basically the same syntax) variables ... would be counter-productive, and a little weird.

**Pull request merged**
